model:
  model_id: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
  device: cuda
  dtype: bfloat16

experiment:
  max_tokens: 2048
  temperature: 0.6
  n_samples: 32
  output_path: ../final_runs/GPQA/reason-R1-D-Qwen-7B--temp-0.6--samples-32--max-2048.jsonl

  reasoning: true

benchmark:
  type: gsm8k_jsonl
  params:
    path: ../datasets/GPQA/test.jsonl

verifier:
  type: gpqa_mc
